config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations',
                                    confirmations: 'users/confirmations' }

  root to: 'home#index'

  get '/auth/failure' => 'omniauth_callbacks#failure'

  resources :categories do
    resources :chemicals, only: [:show, :new,
                                 :edit, :update, :destroy, :create]
  end

  get '/chemicals', to: 'chemicals#index'

  resources :chemicals do
    resources :safety_precautions, only: [:show, :new,
                                          :edit, :update, :destroy, :create]
  end

  get 'safety_precautions', to: 'safety_precautions#index'

  resources :chemicals do
    resources :items
  end
end

app/models/safety_precaution.rb
# frozen_string_literal: true

class SafetyPrecaution < ApplicationRecord
  belongs_to :chemical

  mount_uploader :sds_file, SdsFileUploader

  def download_msds
    MsdsDownloadService.new(self).call
  end
end

app/controllers/safety_precautions_controller.rb
# frozen_string_literal: true

class SafetyPrecautionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_chemical, only: [:create, :show, :edit, :update, :destroy]
  before_action :set_safety_precaution, only: [:show, :edit, :update, :destroy]

  def index
    @safety_precautions = SafetyPrecaution.includes(:chemical).all
    @q = SafetyPrecaution.ransack(params[:q])
    @safety_precautions = @q.result.includes(:chemical)
  end

  def show
    @safety_precaution = @chemical.safety_precaution
  end

  def new
    @safety_precaution = @chemical.build_safety_precaution
  end

  def create
    @safety_precaution = @chemical.build_safety_precaution(safety_precaution_params)
    if @safety_precaution.save
      redirect_to chemical_safety_precaution_path(@chemical, @safety_precaution), notice: I18n.t('shared.created', resource: 'Hazard and Safety sheet')
    else
      flash.now.alert = I18n.t('shared.error_create')
      render :new
    end
  end

  def edit; end

  def update
    if @safety_precaution.update(safety_precaution_params)
      redirect_to chemical_safety_precaution_path(@chemical, @safety_precaution), notice: t('shared.updated', resource: 'Hazard and Safety sheet')
    else
      render :edit
    end
  end

  def destroy
    @safety_precaution.destroy
    redirect_to chemical_safety_precaution_path(@chemical, @safety_precaution), notice: I18n.t('shared.deleted', resource: 'Hazard and Safety sheet')
  end

  private

  def set_chemical
    @chemical ||= Chemical.find(params[:chemical_id])

  end

  def set_safety_precaution
    @safety_precaution = SafetyPrecaution.find(params[:id])
  end


  def safety_precaution_params
    params.require(:safety_precaution).permit(:sds_file, :name_from_sds, :pictogram,
                                              :storage_temperature_range, :signal_word,
                                              :h_codes, :h_statements, :p_codes, :p_statements,
                                              :adr_number, :adr_class, :adr_group, :chemical_id)
  end
end

app/helpers/safety_precautions_helper.rb
# frozen_string_literal: true

module SafetyPrecautionsHelper
end

app/views/safety_precautions/shared/_chemicals_with_safety_precaution.html.haml
.col.md-12.frame-form
  %table.table.table-condensed.center-content
    %thead
      %tr
        %th= t('chemical.columns.image')
        %th= t('chemical.columns.name')
        %th= t('chemical.columns.cas_number')
        %th= t('chemical.columns.category')
        %th= t('chemical.columns.show_msds')

      %tbody
        %tr
          - @safety_precautions.each do |safety_precaution|
            %tr
            - unless safety_precaution.chemical.nil?
              %td= image_tag(safety_precaution.chemical.decorate.show_formula_picture)
              %td= link_to safety_precaution.chemical.decorate.titleize_chemical_name, chemical_safety_precaution_path(safety_precaution.chemical_id, safety_precaution)
              %td= safety_precaution.chemical.cas_number
              %td= safety_precaution.chemical.category.decorate.titleize_category_name
              %td
                = link_to safety_precaution.decorate.show_msds_file, { title: t('shared.download_msds') } do
                  %button.btn.btn-outline-secondary.btn_margin
                    = fa_icon "external-link"

app/views/safety_precautions/shared/_form.html.haml
.row
  .col-md-8
    = simple_form_for [@chemical, @chemical.safety_precaution], html: { multipart: true} do |f|
      = f.input :sds_file, as: :file
      = f.collection_select(:chemical_id, Chemical.where(id: @safety_precaution.chemical_id), :id, :chemical_name, { :prompt => "Select Chemical"}, {:selected => :prompt})
      = f.input :name_from_sds
      = f.input :h_codes
      = f.input :p_codes
      = f.input :h_statements
      = f.input :p_statements
      = f.input :adr_number
      = f.input :adr_group
      = f.button :submit, class: 'btn btn-outline-primary'

app/views/safety_precautions/shared/_safety_attributes.html.haml
%tr
  %td= t("chemical.columns.name")
  %td= @safety_precaution.chemical.chemical_name
  %tr
    %td= image_tag(@safety_precaution.chemical.decorate.show_formula_picture) unless @safety_precaution.chemical.formula_picture.nil?
    %td
      = link_to @safety_precaution.decorate.show_msds_file, { title: t('shared.download_msds') } do
        %button.btn.btn-outline-secondary.btn_margin
          = fa_icon "download"
    %tr
      %td= t('chemical.columns.category')
      %td= @safety_precaution.chemical.category.category_name
      %td= t("chemical.columns.name_form_msds")
      %td= @safety_precaution.name_from_sds
    %tr
      %td= t("chemical.columns.pictogram")
      %td= @safety_precaution.pictogram
      %td= t("chemical.columns.storage_temperature")
      %td= @safety_precaution.storage_temperature_range
    %tr
      %td= t("chemical.columns.signal_word")
      %td= @safety_precaution.signal_word
      %td= t("chemical.columns.h_codes")
      %td= @safety_precaution.h_codes
    %tr
      %td= t("chemical.columns.h_statements")
      %td= @safety_precaution.h_statements
      %td= t("chemical.columns.p_codes")
      %td= @safety_precaution.p_codes
    %tr
      %td= t("chemical.columns.p_statements")
      %td= @safety_precaution.p_statements
      %td= t("chemical.columns.adr_number")
      %td= @safety_precaution.adr_number
    %tr
      %td= t("chemical.columns.adr_class")
      %td= @safety_precaution.adr_class
      %td= t("chemical.columns.adr_group")
      %td= @safety_precaution.adr_group

app/views/safety_precautions/shared/_safety_precaution_attributes_table.html.haml
%a.list-group-item.list-group-item-action.active{:href => "#"}
  %h4 Safety Data Sheet
  %a.list-group-item.list-group-item-action
    %table.table.table-borderless
      - if @safety_precaution.nil? || @safety_precaution.chemical.nil?
        %tr
          %td No data provided
      - else
        = render 'safety_precautions/shared/safety_attributes'

app/views/safety_precautions/shared/_search.html.haml
.jumbotron
  %h3.display-3
  %p.lead A Material Safety Data Sheet (MSDS) contains information on the properties and potential hazards of the material. Read before you start working to know how to use it safely, and what to do if there is an emergency.
  .list-group
    %a.list-group-item.list-group-item-action.active{:href => "#"}
      %h4 Search MSDS sheet
    %a.list-group-item.list-group-item-action
      =render 'safety_precautions/shared/search_msds'
      =render 'safety_precautions/shared/chemicals_with_safety_precaution'
  %hr.my-4/
  %p.lead

app/views/safety_precautions/shared/_search_msds.html.haml
.col.md-12.frame-form
  %table.table.table-condensed
    %thead
    %tr
      %td
        = search_form_for @q, html: {class: "form-tag"} do |f|
          .input-group
            = f.search_field :chemical_chemical_name_cont, placeholder: 'Search MSDS by name', class: "form-control"
            %span.input-group-btn
              = f.submit "Search", class: 'btn btn-secondary'
        = search_form_for @q, html: {class: "form-tag"} do |f|
          .input-group
            = f.search_field :chemical_cas_number_cont, placeholder: 'Search MSDS by cas', class: "form-control"
            %span.input-group-btn
              = f.submit "Search", class: 'btn btn-secondary'

app/views/safety_precautions/shared/_sidebar_msds.html.haml
.card.border-secondary.mb-3{:style => "max-width: 15rem;"}
  .card-header Control Panel
  .card-body
    %table.table.table-condensed
      %tr
        %td
        .row.pull-right
          = link_to new_chemical_safety_precaution_path(@safety_precaution.chemical_id, @safety_precaution.id), { title: t('shared.edit') } do
            %button.btn.btn-outline-success.btn_margin
              = fa_icon "plus"
          = link_to edit_chemical_safety_precaution_path(@safety_precaution.chemical_id, @safety_precaution.id), {title: "edit"} do
            %button.btn.btn-outline-warning.btn_margin
              = fa_icon "edit"
          = link_to chemical_safety_precaution_path(@safety_precaution.chemical_id, @safety_precaution.id), { method: :delete, title: "delete"} do
            %button.btn.btn-outline-danger.btn_margin
              = fa_icon "trash"
    .col-md-10.btn_margin
      = link_to t('chemical.columns.new_category'), new_category_path, class: 'btn btn-secondary'
    .col-md-10.btn_margin
      = link_to t('chemical.columns.new_chemical'), new_category_chemical_path(@chemical.category_id, @chemical), class: 'btn btn-secondary'
    .col-md-10.btn_margin
      = link_to t('chemical.columns.add_msds'), new_chemical_safety_precaution_path(@safety_precaution.chemical_id, @safety_precaution.id), class: 'btn btn-secondary'