config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations',
                                    confirmations: 'users/confirmations' }

  root to: 'home#index'

  get '/auth/failure' => 'omniauth_callbacks#failure'

  resources :categories do
    resources :chemicals, only: [:show, :new,
                                 :edit, :update, :destroy, :create]
  end

  get '/chemicals', to: 'chemicals#index'

  resources :chemicals do
    resources :safety_precautions, only: [:show, :new,
                                          :edit, :update, :destroy, :create]
  end

  get 'safety_precautions', to: 'safety_precautions#index'

  resources :chemicals do
    resources :items
  end
end

app/views/layouts/shared/_footer.html.haml
%footer.footer
  .container
    .about.pull-left
      = link_to 'About', root_path
    %ul#footer_nav.pull-right
      = link_to "https://github.com/katguz3485/LabManager" do
        %span.accent.fa.fa-github{"aria-label" => "github"}
      = link_to "https://www.linkedin.com/in/kguzik" do
        %span.accent.fa.fa-linkedin{"aria-label" => "linkedin"}
    %ul#footer_nav-center
      = render 'layouts/shared/logo'

app/views/layouts/shared/_logo.html.haml
= link_to root_path, class: 'logo' do
    = image_tag 'labManagerLogo_flask.png', :height => "30", :width => "30"

app/views/layouts/shared/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/shared/_navigation.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-primary
  .container
    %a.navbar-brand{ href: root_path }
      = image_tag 'labManagerLogo_flask.png', class: 'navbrand-logo'
      = link_to "Lab Manager", root_path, class: 'navbar-brand'
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav.mr-auto
        %li.nav-item
          = link_to t('navbar.chemicals'), chemicals_path
        %li.nav-item
          = link_to t('navbar.categories'), categories_path
        %li.nav-item
          = link_to t('navbar.safety_precautions'), safety_precautions_path
      %ul.nav.navbar-nav.ml-auto
        - if user_signed_in?
          .dropdown.show
            %a#dropdown-menu-link.btn.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              = current_user.email
              %button.avatar{"aria-label" => "User Menu", "data-toggle" => "dropdown", :style => "background-image:url(#{avatar_path(current_user.avatar)})"}
            .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "dropdown-menu-link"}
              = link_to t('navbar.logout'), destroy_user_session_path, method: :delete, class: 'dropdown-item'
        - else
          %li.nav-item
            = link_to t('navbar.signin'), new_user_session_path, class: 'nav-link'
          %li.nav-item
            = link_to t('navbar.signup'), new_user_registration_path, class: 'nav-link'

app/views/layouts/shared/_sidebar.html.haml
.card.border-secondary.mb-3{:style => "max-width: 15rem;"}
  .card-header Control Panel
  .card-body
    %table.table.table-condensed
      %tr
        %td
        .row.pull-right
          = link_to new_category_chemical_path(@chemical.category_id, @chemical), { title: t('shared.edit') } do
            %button.btn.btn-outline-success.btn_margin
              = fa_icon "plus"
          = link_to edit_category_chemical_path(@chemical.category_id, @chemical), {title: "edit"} do
            %button.btn.btn-outline-warning.btn_margin
              = fa_icon "edit"
          = link_to category_chemical_path(@chemical.category_id,@chemical), { method: :delete, title: "delete"} do
            %button.btn.btn-outline-danger.btn_margin
              = fa_icon "trash"
    .col-md-10.btn_margin
      = link_to t('chemical.columns.new_category'), new_category_path, class: 'btn btn-secondary'
    .col-md-10.btn_margin
      = link_to t('chemical.columns.new_chemical'), new_category_chemical_path(category_id: @category.id), class: 'btn btn-secondary'
    .col-md-10.btn_margin
      = link_to t('chemical.columns.new_item'), new_chemical_item_path(@chemical, @item), class: 'btn btn-secondary'
    .col-md-10.btn_margin
      = link_to t('chemical.columns.add_msds'), new_chemical_safety_precaution_path(@chemical, @safety_precaution), class: 'btn btn-secondary'