config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations',
                                    confirmations: 'users/confirmations' }

  root to: 'home#index'

  get '/auth/failure' => 'omniauth_callbacks#failure'

  resources :categories do
    resources :chemicals, only: [:show, :new,
                                 :edit, :update, :destroy, :create]
  end

  get '/chemicals', to: 'chemicals#index'

  resources :chemicals do
    resources :safety_precautions, only: [:show, :new,
                                          :edit, :update, :destroy, :create]
  end

  get 'safety_precautions', to: 'safety_precautions#index'

  resources :chemicals do
    resources :items
  end
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  belongs_to :chemical

  validates :item_owner, :quantity, :amount, presence: true
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_chemical
  before_action :set_category, only: [:create, :edit, :update, :delete]
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def show
    @items = @chemical.items
  end

  def new
    @item = @chemical.items.build
  end

  def create
    @item = @chemical.items.build(item_params)
    if @item.save
      redirect_to category_chemical_path(@chemical.category_id, @chemical), notice: I18n.t('shared.created', resource: 'Items')
    else
      flash.now.alert = I18n.t('shared.error_create')
      render :new
    end
  end

  def edit;
  end

  def update
    if @item.update(item_params)
      redirect_to category_chemical_path(@chemical.category_id, @chemical), notice: t('shared.updated', resource: 'Item')
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to category_chemical_path(@chemical.category_id, @chemical), notice: I18n.t('shared.deleted', resource: 'Item')
  end

  private

  def set_chemical
    @chemical = Chemical.find(params[:chemical_id])
  end

  def set_category
    @category = Category.find(params[:category_id])
  end

  def set_item
    @item = @chemical.items.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:item_owner,
                                 :quantity,
                                 :amount,
                                 :comment,
                                 :daily_usage,
                                 :room,
                                 :shelf,
                                 :number, :chemical_id)
  end
end

app/helpers/items_helper.rb
# frozen_string_literal: true

module ItemsHelper
end

app/views/items/_form.html.haml
.row
  .col-md-12
    = simple_form_for [@chemical, @item], html: { multipart: true} do |f|
      = f.input :item_owner, collection: [:group1, :group2, :group3]
      = f.input :quantity
      = f.input :amount
      = f.input :comment
      = f.input :daily_usage
      = f.input :present_in_respiratory_zone, as: :boolean, checked_value: true, unchecked_value: false
      = f.input :room
      = f.input :shelf
      = f.input :number
      = f.button :submit, class: 'btn btn-outline-success'

app/views/items/_items_table.html.haml
%a.list-group-item.list-group-item-action.active{:href => "#"}
  %h4 Items
  %a.list-group-item.list-group-item-action
    %table.table.table-borderless
      %tr

        - @items.each do |item|
          %tr
            %td= item.chemical.chemical_name
            %td= item.decorate.item_place
            %td= item.decorate.item_stock
            %td= link_to 'New', new_chemical_item_path(item.chemical_id, item),class: 'btn btn-primary btn-xs'
            %td= link_to 'Edit', edit_chemical_item_path(item.chemical_id, item), class: 'btn btn-primary btn-xs'
            %td= link_to 'Destroy',  chemical_item_path(item.chemical_id, item),class: 'btn btn-primary btn-xs', method: :delete, data: { confirm: 'Are you sure?' }

app/views/items/edit.html.haml
%h1 Editing item

= render 'form'

= link_to 'Show', chemical_item_path(@item.chemical_id, @item)

= link_to 'Back', chemicals_path

app/views/items/new.html.haml
%h1 New item

= render 'form'

= link_to 'Back', chemical_items_path(@item.chemical_id, @item)